Fixed compiling lib7z_facade.cpp with Visual Studio 2013
Commit c43f3f0c683841f7b2bd62ce8c1556f2e5412d4d introduced a usage of
localtime_s for non-MinGW Windows builds. Visual Studio 2013 complained
about this, saying

  ..\..\..\..\source\src\libs\installer\lib7z_facade.cpp(331) : error C3861: 'localtime_s': identifier not found

The MSDN explains that <time.h> should be included, so let's do that to
make the build succeed.

Change-Id: I8447ed0c97480485e4219f6e413b05d80be6ef63
Reviewed-by: Karsten Heimrich <karsten.heimrich@theqtcompany.com>